#spring:
#  application:
#    name: onlineshop
#
#  data:
#    redis:
#      port: 6379
#      host: localhost
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/shopstore
#    username: root
#    password: YES
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    name: shopstore
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health
#
#server:
#  port: 8080